name: Manage Datadog Monitor

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Enable or disable the monitor'
        required: true
        default: 'disable'
        type: choice
        options:
          - enable
          - disable
      monitor_id:
        description: '176133455'
        required: true

jobs:
  manage-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Call Datadog API to enable/disable monitor
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          MONITOR_ID: ${{ github.event.inputs.monitor_id }}
          ACTION: ${{ github.event.inputs.action }}
        run: |
          if [ "$ACTION" == "disable" ]; then
            curl -X PUT "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}" \
              -H "DD-API-KEY: $DD_API_KEY" \
              -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
              -H "Content-Type: application/json" \
              -d '{"disabled": true}'
          else
            curl -X PUT "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}" \
              -H "DD-API-KEY: $DD_API_KEY" \
              -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
              -H "Content-Type: application/json" \
              -d '{"disabled": false}'
          fi
