name: Manage Datadog Monitor

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Enable or disable the monitor'
        required: true
        default: 'disable'
        type: choice
        options:
          - enable
          - disable
      monitor_id:
        description: 'Datadog Monitor ID'
        required: true

jobs:
  manage-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and update monitor
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          MONITOR_ID: ${{ github.event.inputs.monitor_id }}
          ACTION: ${{ github.event.inputs.action }}
        run: |
          echo "Fetching monitor definition..."
          curl -s -X GET "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}" \
            -H "DD-API-KEY: $DD_API_KEY" \
            -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
            -H "Content-Type: application/json" > monitor.json

          echo "Modifying monitor disabled flag..."
          if [ "$ACTION" == "disable" ]; then
            jq '. + {disabled: true}' monitor.json > updated_monitor.json
          else
            jq '. + {disabled: false}' monitor.json > updated_monitor.json
          fi

          echo "Updating monitor in Datadog..."
          curl -s -X PUT "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}" \
            -H "DD-API-KEY: $DD_API_KEY" \
            -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
            -H "Content-Type: application/json" \
            -d @updated_monitor.json
