name: Manage Datadog Monitor with Tag "informatica_dev"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Mute or unmute the monitor(s) with tag "informatica_dev"'
        required: true
        default: 'mute'
        type: choice
        options:
          - mute
          - unmute

jobs:
  manage-informatica-dev-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Manage monitor with tag "informatica_dev"
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          TAG: informatica_dev
          ACTION: ${{ github.event.inputs.action }}
        run: |
          echo "Searching for monitor(s) with tag: ${TAG}"
          RESPONSE=$(curl -s -X GET "https://api.datadoghq.com/api/v1/monitor/search?query=tag:${TAG}" \
            -H "DD-API-KEY: $DD_API_KEY" \
            -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
            -H "Content-Type: application/json")

          echo "API response: $RESPONSE"
          MONITOR_IDS=$(echo "$RESPONSE" | jq -r '.monitors[]?.id')

          if [ -z "$MONITOR_IDS" ]; then
            echo "No monitors found with tag=${TAG}"
            exit 1
          fi

          for MONITOR_ID in $MONITOR_IDS; do
            if [ "$ACTION" == "mute" ]; then
              echo "Muting monitor $MONITOR_ID..."
              curl -s -X POST "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}/mute" \
                -H "DD-API-KEY: $DD_API_KEY" \
                -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
                -H "Content-Type: application/json"
            elif [ "$ACTION" == "unmute" ]; then
              echo "Unmuting monitor $MONITOR_ID..."
              curl -s -X POST "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}/unmute" \
                -H "DD-API-KEY: $DD_API_KEY" \
                -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
                -H "Content-Type: application/json"
            else
              echo "Invalid action: $ACTION"
              exit 1
            fi
          done
