name: Manage Datadog Monitors by Service Tag

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Mute or unmute the monitor(s)'
        required: true
        default: 'mute'
        type: choice
        options:
          - mute
          - unmute
      service:
        description: 'Datadog service tag (e.g., informatica_metadoc_dev)'
        required: true

jobs:
  manage-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Mute or unmute monitors by service tag
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          SERVICE: ${{ github.event.inputs.service }}
          ACTION: ${{ github.event.inputs.action }}
        run: |
          echo "Querying monitors with service tag: ${SERVICE}"

          # Encode the full query: service:"your_tag"
          ENCODED_QUERY=$(jq -rn --arg s "service:\"${SERVICE}\"" '$s | @uri')

          # Perform the search
          RESPONSE=$(curl -s -X GET "https://api.datadoghq.com/api/v1/monitor/search?query=${ENCODED_QUERY}" \
            -H "DD-API-KEY: $DD_API_KEY" \
            -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
            -H "Content-Type: application/json")

          echo "API response: $RESPONSE"
          MONITOR_IDS=$(echo "$RESPONSE" | jq -r '.monitors[]?.id')

          if [ -z "$MONITOR_IDS" ]; then
            echo "No monitors found with service=${SERVICE}"
            exit 1
          fi

          for MONITOR_ID in $MONITOR_IDS; do
            if [ "$ACTION" == "mute" ]; then
              echo "Muting monitor $MONITOR_ID..."
              curl -s -X POST "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}/mute" \
                -H "DD-API-KEY: $DD_API_KEY" \
                -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
                -H "Content-Type: application/json"
            elif [ "$ACTION" == "unmute" ]; then
              echo "Unmuting monitor $MONITOR_ID..."
              curl -s -X POST "https://api.datadoghq.com/api/v1/monitor/${MONITOR_ID}/unmute" \
                -H "DD-API-KEY: $DD_API_KEY" \
                -H "DD-APPLICATION-KEY: $DD_APP_KEY" \
                -H "Content-Type: application/json"
            else
              echo "Invalid action: $ACTION"
              exit 1
            fi
          done
